// Command worldmap regenerates web/static/world.svg, the offline base map used
// by the console dashboard.
//
// It reads Natural Earth country geometry (public domain, distributed as
// TopoJSON by the world-atlas project) and the ISO 3166 numeric-to-alpha-2
// table, projects the polygons equirectangularly and writes one SVG path per
// country tagged with its alpha-2 code, which is what the geolocation database
// returns. The result is committed so the running service needs no network
// access and the page needs no mapping library.
//
// Usage:
//
//	go run ./tools/worldmap -out web/static/world.svg
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	defaultTopo = "https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json"
	defaultISO  = "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json"
)

type topology struct {
	Transform struct {
		Scale     [2]float64 `json:"scale"`
		Translate [2]float64 `json:"translate"`
	} `json:"transform"`
	Arcs    [][][2]float64 `json:"arcs"`
	Objects struct {
		Countries struct {
			Geometries []geometry `json:"geometries"`
		} `json:"countries"`
	} `json:"objects"`
}

type geometry struct {
	Type       string          `json:"type"`
	ID         string          `json:"id"`
	Arcs       json.RawMessage `json:"arcs"`
	Properties struct {
		Name string `json:"name"`
	} `json:"properties"`
}

type isoRow struct {
	Name        string `json:"name"`
	Alpha2      string `json:"alpha-2"`
	CountryCode string `json:"country-code"`
}

func main() {
	var (
		topoSrc = flag.String("topojson", defaultTopo, "TopoJSON source (URL or path)")
		isoSrc  = flag.String("iso", defaultISO, "ISO 3166 table (URL or path)")
		out     = flag.String("out", "web/static/world.svg", "output SVG path")
		width   = flag.Float64("width", 1000, "viewBox width")
		height  = flag.Float64("height", 500, "viewBox height")
		latMax  = flag.Float64("lat-max", 84, "northern clip latitude")
		latMin  = flag.Float64("lat-min", -56, "southern clip latitude")
		prec    = flag.Int("precision", 1, "decimal places in path coordinates")
	)
	flag.Parse()

	topoRaw, err := fetch(*topoSrc)
	if err != nil {
		log.Fatalf("topojson: %v", err)
	}
	isoRaw, err := fetch(*isoSrc)
	if err != nil {
		log.Fatalf("iso table: %v", err)
	}

	var topo topology
	if err := json.Unmarshal(topoRaw, &topo); err != nil {
		log.Fatalf("decode topojson: %v", err)
	}
	var isoRows []isoRow
	if err := json.Unmarshal(isoRaw, &isoRows); err != nil {
		log.Fatalf("decode iso table: %v", err)
	}
	numericToAlpha := map[string]isoRow{}
	for _, r := range isoRows {
		numericToAlpha[strings.TrimLeft(r.CountryCode, "0")] = r
	}

	// TopoJSON stores arcs as quantised deltas; rebuild absolute positions once.
	arcs := make([][][2]float64, len(topo.Arcs))
	for i, arc := range topo.Arcs {
		var x, y float64
		pts := make([][2]float64, len(arc))
		for j, d := range arc {
			x += d[0]
			y += d[1]
			pts[j] = [2]float64{
				x*topo.Transform.Scale[0] + topo.Transform.Translate[0],
				y*topo.Transform.Scale[1] + topo.Transform.Translate[1],
			}
		}
		arcs[i] = pts
	}

	project := func(lon, lat float64) (float64, float64) {
		if lat > *latMax {
			lat = *latMax
		}
		if lat < *latMin {
			lat = *latMin
		}
		x := (lon + 180) / 360 * *width
		y := (*latMax - lat) / (*latMax - *latMin) * *height
		return x, y
	}

	type shape struct {
		code string
		name string
		d    string
	}
	var shapes []shape

	for _, g := range topo.Objects.Countries.Geometries {
		if g.ID == "010" || g.ID == "10" { // Antarctica: clipped away by the projection
			continue
		}
		row, ok := numericToAlpha[strings.TrimLeft(g.ID, "0")]
		code := row.Alpha2
		name := g.Properties.Name
		if !ok {
			code = ""
		}
		if name == "" {
			name = row.Name
		}

		var polygons [][][]int
		switch g.Type {
		case "Polygon":
			var rings [][]int
			if err := json.Unmarshal(g.Arcs, &rings); err != nil {
				log.Fatalf("%s: %v", name, err)
			}
			polygons = [][][]int{rings}
		case "MultiPolygon":
			if err := json.Unmarshal(g.Arcs, &polygons); err != nil {
				log.Fatalf("%s: %v", name, err)
			}
		default:
			continue
		}

		var d strings.Builder
		for _, rings := range polygons {
			for _, ring := range rings {
				pts := ringPoints(arcs, ring)
				if len(pts) < 3 {
					continue
				}
				writeRing(&d, pts, project, *prec)
			}
		}
		if d.Len() == 0 {
			continue
		}
		shapes = append(shapes, shape{code: code, name: name, d: d.String()})
	}

	sort.Slice(shapes, func(i, j int) bool { return shapes[i].name < shapes[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Generated by tools/worldmap on %s.\n", time.Now().UTC().Format("2006-01-02"))
	b.WriteString("     Geometry: Natural Earth 1:110m (public domain) via world-atlas.\n")
	b.WriteString("     Country codes: ISO 3166-1 alpha-2. Do not edit by hand. -->\n")
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %g %g" class="worldmap" role="img" aria-label="World map">`+"\n",
		*width, *height)
	b.WriteString(`<g class="worldmap-land">` + "\n")
	for _, s := range shapes {
		if s.code == "" {
			fmt.Fprintf(&b, `<path class="cc" d="%s"/>`+"\n", s.d)
			continue
		}
		fmt.Fprintf(&b, `<path class="cc" id="cc-%s" data-cc="%s" data-name="%s" d="%s"><title>%s</title></path>`+"\n",
			s.code, s.code, escape(s.name), s.d, escape(s.name))
	}
	b.WriteString("</g>\n</svg>\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d countries, %d bytes)\n", *out, len(shapes), b.Len())
}

func ringPoints(arcs [][][2]float64, ring []int) [][2]float64 {
	var pts [][2]float64
	for _, idx := range ring {
		var arc [][2]float64
		if idx < 0 {
			src := arcs[^idx]
			arc = make([][2]float64, len(src))
			for i := range src {
				arc[i] = src[len(src)-1-i]
			}
		} else {
			arc = arcs[idx]
		}
		if len(pts) > 0 && len(arc) > 0 {
			arc = arc[1:] // the shared endpoint is already present
		}
		pts = append(pts, arc...)
	}
	return pts
}

func writeRing(d *strings.Builder, pts [][2]float64, project func(float64, float64) (float64, float64), prec int) {
	var lastX, lastY string
	first := true
	for _, p := range pts {
		x, y := project(p[0], p[1])
		sx := strconv.FormatFloat(x, 'f', prec, 64)
		sy := strconv.FormatFloat(y, 'f', prec, 64)
		if sx == lastX && sy == lastY {
			continue // collapsed by rounding
		}
		if first {
			d.WriteString("M" + sx + " " + sy)
			first = false
		} else {
			d.WriteString("L" + sx + " " + sy)
		}
		lastX, lastY = sx, sy
	}
	if !first {
		d.WriteString("Z")
	}
}

func escape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

func fetch(src string) ([]byte, error) {
	if !strings.HasPrefix(src, "http://") && !strings.HasPrefix(src, "https://") {
		return os.ReadFile(src)
	}
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(src)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", src, resp.Status)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 32<<20))
}
